cita-cloud/controller

Cargo.toml
src/chain.rs
src/controller.rs
src/genesis.rs
src/main.rs

remove proof and executed_block_hash from block header
argument of commit_block change to ProposalWithProof

change_20200903

---

Cargo.toml

https://github.com/hannobraun/inotify/issues/164

rollback inotify to old version

---

Cargo.toml

add debug info, only line tables and exclude dependencies

---

src/controller.rs

fix https://github.com/cita-cloud/controller_poc/issues/25

implement getBlockByHash

---

src/controller.rs

fix https://github.com/cita-cloud/controller_poc/issues/31

fix sync tx failed

---

src/main.rs
src/util.rs

fix https://github.com/cita-cloud/controller_poc/issues/36

fix init failed

---

src/main.rs

fix https://github.com/cita-cloud/controller_poc/issues/40

fix restart failed

---

src/chain.rs
src/controller.rs
src/main.rs
src/sync.rs
src/util.rs

修复 https://github.com/cita-cloud/controller_poc/issues/30
修复 https://github.com/cita-cloud/controller_poc/issues/24
add pre state_root and proof into proposal
顺便改了一个 typo
修复多处bug

add pre state_root and proof into proposal

---

src/chain.rs
src/controller.rs

process block when commit block even block has synced
remove performance log

process block when commit block even block has synced

---

src/chain.rs
src/controller.rs
src/main.rs
src/util.rs

fix https://github.com/cita-cloud/cita_cloud_proto/issues/8
fix https://github.com/cita-cloud/controller_poc/issues/53

add height in proposal and ConsensusConfiguration

---

src/auth.rs
src/controller.rs

fix https://github.com/cita-cloud/controller_poc/issues/58

ignore interal err

---

src/main.rs
src/util.rs

follow https://github.com/cita-cloud/rfcs/issues/3

handle storage error

---

src/controller.rs
src/main.rs
src/util.rs
src/utxo_set.rs

fix https://github.com/cita-cloud/controller_poc/issues/63

fix move tx;write tx after check;fix clippy

---

src/chain.rs

Without the `block_in_place`，this op will block and prevent other tasks in the worker's local task queue from scheduling.

fix blocking op in check_transactions

---

src/main.rs
src/utxo_set.rs

fix: sys-config is not persisted when init

---

src/chain.rs
src/controller.rs

Confirm executor when start

---

src/config.rs
src/main.rs

feat: add block growth check
optim: sync logical

feat: add inner block growth check

---

Cargo.toml
README.md
example/config.toml
src/config.rs
src/controller.rs
src/utxo_set.rs

* split node address and validator address, add validator_address_len

support consensus_overlord

---

src/config.rs
src/main.rs
src/util.rs

fix https://github.com/cita-cloud/controller/issues/157

set keep alive

---

src/controller.rs

broadcast  status when height increased

chore: broadcast increased status

---

src/chain.rs
src/controller.rs

fix https://github.com/cita-cloud/controller/issues/163

optim: get bn

---

src/chain.rs
src/health_check.rs

fix https://github.com/cita-cloud/controller/issues/162

Fix check proposal failed

---

README.md
example/config.toml
src/config.rs
src/utxo_set.rs

related to https://github.com/cita-cloud/cloud-config/issues/49

mv quota limit form controller config to system config

---

src/chain.rs

fix https://github.com/cita-cloud/controller/issues/188

when wal redo ignore some check

---

src/main.rs

Node got proposal in sync mode can't do syncing

fix: node in sync mode

---

Cargo.toml
src/auth.rs
src/chain.rs
src/controller.rs
src/main.rs
src/node_manager.rs
src/system_config.rs
src/util.rs

原proto拆分后，无法编译
改用cloud-common-rs

use common

---

src/main.rs
src/node_manager.rs

optim: process_network_msg log print

---

src/controller.rs

fix https://github.com/cita-cloud/controller/issues/205

fix: check timestamp

---

src/chain.rs

可以避免因io问题引起，wal清理不成功时出块过程被中断，等到再次finalize_block时报错ReenterBlock
fix https://github.com/cita-cloud/controller/issues/214

optim: skip and log ReenterBlock

---

README.md
src/auth.rs
src/chain.rs
src/controller.rs
src/genesis.rs
src/health_check.rs
src/main.rs
src/node_manager.rs
src/pool.rs
src/protocol/sync_manager.rs
src/system_config.rs
src/util.rs

1. 统一日志输出格式
2. 添加pool_quota
3. u64_decode移到util，所有解析u64都使用u64_decode
4. 排查节点地址、origin混用，日志统一输出origin

optim: log

---

src/chain.rs

* move update systemconfig after exec block; 
* ignore update if empty block; 
* add log
related to: https://github.com/cita-cloud/controller/issues/218

optimize finalize block

---

src/chain.rs

fix https://github.com/cita-cloud/controller/pull/219

update auth even empty block

---

src/controller.rs
src/grpc_client/executor.rs
src/grpc_client/mod.rs
src/grpc_server/rpc_server.rs

1. add new rpc method
2. add evm client

feat: support cross chain proof

---

src/chain.rs
src/controller.rs
src/grpc_client/storage.rs
src/grpc_server/consensus_server.rs
src/grpc_server/network_server.rs
src/main.rs
src/system_config.rs

在 https://github.com/cita-cloud/controller/pull/235 之后合

refactor and optim
